## Journal articles
* Juan J. Durillo, Philipp Gschwandtner, Klaus Kofler, and Thomas Fahringer. Multiobjective region-aware optimization of parallel programs.Parallel Computing, 2018.
* Thanh-Phuong Pham, Juan J. Durillo, and Thomas Fahringer. Predicting workflow task execution time in the cloud using a two-stage machine learning approach.Accepted for publication in IEEE Transactions on Cloud Computing, 2017.
* Cristbal Barba-Gonzlez, Jos Garca-Nieto, Antonio J. Nebro, Jos A. Cordero, Juan J. Durillo, Ismael Navas-Delgado, and Jos F. Aldana-Montes. jmetalsp: A framework for dynamic multi-objective big data optimization.Applied Soft Computing, 2017.
* Cristian Zambrano-Vega, Antonio J. Nebro, Juan J. Durillo, Jos ́e Garc ́ıa-Nieto, and Jos ́e F. Aldana-Montes. Multiple sequence alignment with multi-objective metaheuristics. a comparative study.Acceted for publication in International Journal of Intelligent Systems, 2017.
* Francisco Luna, Gustavo R. Zavala, Antonio J. Nebro, Juan J. Durillo, and Carlos A. Coello Coello. Distributed multi-objective metaheuristics for real-world structural optimization problems.The Computer Journal, 59(6):777, 2016.
* Gustavo R. Zavala, Antonio J. Nebro, Juan J. Durillo, and Francisco Luna. Integrating a multi-objective optimization framework into a structural design software.Advances in Engineering Software, 76(Complete):161–170, 2014.
* Juan J. Durillo, Radu Prodan, and Jorge G. Barbosa. Pareto tradeoff scheduling of workflows on federated commercial clouds.Simulation Modelling Practice and Theory 58:95–111, 2015.
* J.J. Durillo and T. Fahringer. From single- to multi-objective auto-tuning of programs: Advantages and implications.Scientific Programming, 22(4):285–297, 2014.
* J. J. Durillo and R. Prodan. Multi-objective workflow scheduling in amazon ec2. Cluster Computing, 7(2):169–189, 2014.
* J. J. Durillo, V. Nae, and R. Prodan. Multi-objective energy-efficient workflow scheduling using list-based heuristics. Future Generation of Computer Systems, 6:221–236,2014.
* J.J. Durillo and A. J. Nebro. jmetal: A java framework for multi-objective optimization.Advances in Engineering Software, 42(10):760–771, 2011. 
* A. J. Nebro, F. Luna, E. Alba, B. Dorronsoro, J. J. Durillo, and A. Beham. Abyss: Adapting scatter search to multiobjective optimization.IEEE Transactions on Evolutionary Computation, 12(4):439–457, 2008. 
* J. J. Durillo, A. J. Nebro, C. A. Coello Coello, J. Garc ́ıa-Nieto, F. Luna, and E. Alba. A study of multiobjective metaheuristics when solving parameter scalable problems. IEEE Transactions on Evolutionary Computation, 14(4):618–635, 2010.
* F. Luna, J. J. Durillo, A. J. Nebro, and E. Alba. Evolutionary algorithms for solving the automatic cell planning problem: a survey.Engineering Optimization, 42(7):671–690, 2010.
* A. J. Nebro, J. J. Durillo, F. Luna, B. Dorronsoro, and E. Alba. Mocell: A cellular genetic algorithm for multiobjective optimization.International Journal of Intelligent Systems, 24(7):726–746, 2009.
* F. Luna, Antonio J. Nebro, E. Alba, and J. J. Durillo. Solving large-scale real-world telecommunication problems using a grid-based genetic algorithm.Engineering Opti-
mization, 40(11):1067–1084, 2008. 
* J. J. Durillo, A. J. Nebro, F. Luna, C. A. Coello Coello, and E. Alba. Convergence speed in multi-objective metaheuristics: Efficiency criteria and empirical study.International Journal for Numerical Methods in Engineering, 84(11):1344–1375, 2010.
* J. J. Durillo, Y. Zhang, E. Alba, M. Harman, and A. J. Nebro. A study of the bi-objective next release problem.Empirical Software Engineering, 16(1):29–60, 2011.

## Book chapters
* A. J. Nebro and J. J. Durillo. On the Effect of Applying a Steady-State Selection Scheme in the Multi-Objective Genetic Algorithm NSGA-II, volume 193 ofStudies in Computational Intelligence. Springer, 2009. 
* J. J. Durillo, A. J. Nebro, J. Garc ́ıa-Nieto, and E. Alba. On the Velocity Update in Multi-objective Particle Swarm Optimizers, volume 272 ofStudies in Computational Intelligence. Springer, 2010. 
* A. J. Nebro, J. J. Durillo, F. Luna, and E. Alba.Evaluating New Advanced Multiobjective Metaheuristics. Wiley, May 2008.

## Conference papers
* Biagio Cosenza, Juan J. Durillo, Stefano Ermon, and Juurlink Ben. Autotuning stencil computations with structural ordinal regression learning. In31st IEEE International Parallel & Distributed Processing Sympossium, 2017. 
* A. J. Nebro, J. J. Durillo, and M. Vergne. Redesigning the jmetal multi-objective opti mization framework. InGenetic and Evolutionary Computation Conference, GECCO 2015, Madrid, Spain, July 11-15, 2015, Companion Material Proceedings, pages 1093–1100, 2015.
* L. Ayuso, J. J. Durillo, B. Kornberger, M. Schifko, and T. Fahringer. Parallelizationand optimization of a CAD model processing tool from the automotive industry to distributed memory parallel computers. InParallel Processing and Applied Mathematics- 11th International Conference, PPAM 2015, Krakow, Poland, September 6-9, 2015. 
* Jerry Swan, S. Adriaensen, M. Bishr, E. K. Burke, J. A. Clark, P. De Causmaecker, J. Durillo, K. Hammond, E. Hart, C. G. Johnson, Z. A. Kocsis, B. Kovitz, K. Krawiec, S. Martin, L. L. Minku J. J. Merelo, E. Ozcan, G. L. Pappa, E. Pesch, P. Garcia-S ́anchez, A. Schaerf, K. Sim, J. Smith, T. Stuetzle, S. Vo, S. Wagner, and X. Yao. A research agenda for metaheuristic standardization. InMIC 2015: The XI Metaheuristics International Conference, June 2015.
* P. Gschwandtner, J. J. Durillo, and T. Fahringer. Multi-objective auto-tuning with insieme: Optimization and trade-off analysis for time, energy and resource usage. In Euro-Par 2014 Parallel Processing - 20th International Conference, Porto, Portugal, August 25-29, 2014. Proceedings, pages 87–98, 2014.
* J. J. Durillo and R. Prodan. Workflow scheduling on federated clouds. InEuro-Par 2014 Parallel Processing - 20th International Conference, Porto, Portugal, August 25-29,2014. Proceedings, pages 318–329, 2014.
* F. Luna, G. R. Zavala, A. J. Nebro, J. J. Durillo, and C. A. Coello Coello. Solving a real-world structural optimization problem with a distributed SMS-EMOA algorithm. InEighth International Conference on P2P, Parallel, Grid, Cloud and Internet Computing, 3PGCIC 2013, Compiegne, France, October 28-30, 2013, pages 600–605, 2013.
* A. J. Nebro, J. J. Durillo, M. Machin Navas, C. A. Coello Coello, and B. Dorronsoro. A study of the combination of variation operators in the NSGA-II algorithm. In Advances in Artificial Intelligence - 15th Conference of the Spanish Association for Artificial Intelligence, CAEPIA 2013, Madrid, Spain, September 17-20, 2013. Proceedings, pages 269–278, 2013.
* A. J. Nebro, J. J. Durillo, and C. Coello. Analysis of leader selection strategies in a multi-objective particle swarm optimizer. InEvolutionary Computation (CEC), 2013 IEEE Congress on, pages 3153–3160. IEEE Computer Society Press, July 2013.
* J. J. Durillo, V. Nae, and R. Prodan. Multi-objective workflow scheduling: An analysis of the energy efficiency and makespan tradeoff. InCluster, Cloud and Grid Computing (CCGrid), 2013 13th IEEE/ACM International Symposium on, pages 203–210. IEEE Computer Society Press, May 2013.
* H. Jordan, P. Thoman, J.J. Durillo, S. Pellegrini, P. Gschwandtner, T. Fahringer, and H. Moritsch. A multi-objective auto-tuning framework for parallel codes. InProceedings of the International Conference on High Performance Computing, Networking, Storage and Analysis, pages 10:1–10:12. IEEE Computer Society Press, November 2012.
* J.J. Durillo, H.M. Fard, and R. Prodan. Moheft: A multi-objective list-based method for workflow scheduling. InCloud Computing and Technology and Science, 4th IEEE International Conference on, pages 185–192. IEEE Computer Society Press, December 2012.
* J.J. Laredo, B. Dorronsoro, J. Pecero, P. Bouvry, J.J. Durillo, and C. Fernandes. Designing a self-organized approach for scheduling bag-of-tasks. InP2P, Parallel, Grid, Cloud and Internet Computing (3PGCIC), 2012 Seventh International Conference on, pages 315–320. IEEE Computer Society Press, November 2012.
* J.J. Durillo H. M. Fard, R. Prodan and T. Fahringer. A multi-objective approach for workflow scheduling in heterogeneous environments. InCluster, Cloud and Grid Computing (CCGrid), 2012 12th IEEE/ACM International Symposium on, pages 300–309. IEEE Computer Society Press, May 2012.
* J.J. Durillo, Q. Zhang, A. J. Nebro, and E. Alba. Distribution of computational effort in parallel moea/d. In C.A. Coello Coello, editor,Learning and Intelligent Optimization. 5th International Conference, LION 5, volume 6683 ofLNCS, pages 488–502. Springer, January 2011.
* J.J. Durillo, A.J. Nebro, and E. Alba. The jmetal framework for multi-objective optimization: Design and architecture. InEvolutionary Computation (CEC), 2010 IEEE Congress on, pages 4138–4325. IEEE Computer Society Press, July 2010.
* A. J. Nebro and J.J. Durillo. Study of the parallelization of the multi-objective metaheuristics moea/d. In C. Blum and R. Battiti, editors,Learning and Intelligent  Optimization. 4th International Conference, LION 4, volume 6073 ofLNCS, pages 303–317. Springer, January 2010.
* Y. Zhang, E. Alba, J.J. Durillo, S. Eldh, and M. Harman. Today/future importance analysis. In Franz Rothlauf, editor,Genetic and Evolutionary Computation Confer-ence, GECCO 2009, pages 1357–1364. ACM press, July 2009.
* J. J. Durillo, Y. Zhang, E. Alba, and A. J. Nebro. A study of the multi-objective next release problem. In1st International Symposium on Search Based Software Engineering, pages 49–58. IEEE Computer Society Press, May 2009. 
* F. Luna, J. J. Durillo, A. J. Nebro, and E. Alba. A scatter search approach for solving the automatic cell planning problem. In I. Lirkov, S. Margenov, and J. Wa ́sniewski, editors,Large-Scale Scientific Computing. 7th International Conference, LSSC 2009, volume 5910 ofLNCS, pages 334–342. Springer, June 2010.
* J.J. Durillo, A.J. Nebro, F. Luna, and E. Alba. On the effect of the steady-state selection scheme in multi-objective genetic algorithms. In C.M. Fonseca, X. Gandibleux, J.K. Hao, and M. Sevaux, editors,Evolutionary Multi-Criterion Optimization. 5th International Conference, EMO 2009, volume 5467 ofLNCS, pages 183–197. Springer, March 2009.
* J.J. Durillo, J. Garc ́ıa-Nieto, A.J. Nebro, C. A. Coello Coello, F. Luna, and E. Alba. Multi-objective particle swarm optimizers: An experimental comparison. In C.M. Fonseca, X. Gandibleux, J.K. Hao, and M. Sevaux, editors,Evolutionary Multi-Criterion Optimization. 5th International Conference, EMO 2009, volume 5467 ofLNCS, pages 495–509. Springer, March 2009. 
* A. J. Nebro, J. J. Durillo, J. Garc ́ıa-Nieto, C. A. Coello Coello, F. Luna, and E. Alba. Smpso:a new pso-based metaheuristic for multi-objective optimization. In Computa tional intelligence in miulti-criteria decision-making, 2009. MCDM 09. IEEE Symposium on, pages 66–73. IEEE Computer Society Press, April 2009.
* J J. Durillo, A. J. Nebro, F. Luna, and E. Alba. Solving three-objective optimization problems using a new hybrid cellular genetic algorithm. In G. Rudolph, T. Jansen, S.M. Lucas, C. Poloni, and N. Beume, editors,Parallel Problem Solving from Nature - PPSN X, volume 5199 ofLNCS, pages 661–670. Springer, September 2008. 
* A. J. Nebro, J. J. Durillo, C.A. Coello Coello, F. Luna, and E. Alba. A study of convergence speed in multi-objective metaheuristics. In G. Rudolph, T. Jansen, S.M. Lucas, C. Poloni, and N. Beume, editors,Parallel Problem Solving from Nature - PPSN X, volume 5199 ofLNCS, pages 763–772. Springer, September 2008. 
* J. J. Durillo, A. J. Nebro, C. A. Coello Coello, F. Luna, and E. Alba. A comparative study of the effect of parameter scalability in multi-objective metaheuristics. In Evolutionary Computation, 2008. CEC 2008. (IEEE World Congress on Computational Intelligence). IEEE Congress on, pages 1893–1900. IEEE Computer Society Press, July 2008.

## Workshop papers
* Philipp Gschwandtner Klaus Kofler, Juan J. Durillo and Thomas Fahringer. A region-aware multi-objective auto-tuner for parallel programs. In 10th International Workshop on Parallel Programming Models and Systems Software for High-End Computing (P2S2), 2017.
* Biagio Cosenza, Juan J Durillo, Stefano Ermon, and Ben Juurlink. Stencil autotuning with ordinal regression. InProceedings of the 20th International Workshop on Software and Compilers for Embedded Systems, pages 72–75. ACM, 2017.
* A. Nebro, C. Zambrano-Vega, J. J. Durillo, and J. F. Aldana Montes. A study of multiple sequences aligment with multi-objective metaheuristics. In 7th European Simposium on Computational Intelligence and Mathematics, pages 156–161, 2015.
* J. J. Durillo, R. Prodan, and Weicheng H.Workflow Scheduling in Amazon EC2, pages 374–383. Springer Berlin Heidelberg, Berlin, Heidelberg, 2014. 
R Ferreira da Silva, Thomas Fahringer, Juan J Durillo, and Ewa Deelman. A unified approach for modeling and optimization of energy, makespan and reliability for scientific workflows on large-scale computing infrastructures. InWorkshop on Modeling &  Simulation of Systems and Applications, 2014.
* J. J. Durillo, A. J. Nebro, F. Luna, and E. Alba. A study of master-slave approaches to parallelize NSGA-II. InParallel and Distributed Processing, 2008. IPDPS 2008. IEEE International Symposium on, pages 1–8. IEEE Computer Society Press, May 2008.
